### ISSUE TITLE
Add a `fullScalaVersion` field in `Artifact`

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#1024]
### Motivation

Sometimes we want to know which version of the compiler are used by the library authors. We can find this information in the dependencies of an artifact. But it would more convenient to have it directly from the `Artifact` entity.

### Implementation Guideline

- Add a `fullScalaVersion: Option[SemanticVersion]` in the `Artifact` class.
- Add a `full_scala_version` in the `artifacts` table by adding a SQL migration file [here](https://github.com/scalacenter/scaladex/tree/main/modules/infra/src/main/resources/migrations) and adapt the SQL requests in `ArtifactsTable`.
- In `ArtifactConverter` find the full Scala version in the artifact dependencies. Get the version from the `scala3-library` dependency or the `scala-library`. Beware that Scala 3 libraries depend on both `scala3-library` and `scala-library`. 
- Display the full Scala version to the user in the `artifacts.scala.html` template.

### Expectations

The full Scala version of newly published artifacts should appear in the artifact page.

**Comment by WojciechMazur** [comment]
In the context of the Scala 3 LTS vs Scala 3 Next and SIP-51 (drop binary compatibility of Scala 2.13 standard library) it might be useful to present information about major Scala version used to build the project. Some libraries do require Scala 3 Next features and are not released using Scala LTS. Similarly, once some of Scala 2.13 libraries might use backward incompatible features once the SIP-51 introduces them. Presenting information about using Scala major version used for publishing would inform users before-hand and would allow to decide if we want to use/upgrade to newer version library without upgrading used version of Scala. 
We might use `scala3-library_3`and `scala-library_2.13` versions from POM file to gather required information. Then, we can present them in some more readable way. Based on that we might even introduce filters for searching. 

Why introduce special handling when we already have a list of dependencies? 
Let's take a look at first library showing in the Scaladex homepage to me: https://index.scala-lang.org/playframework/playframework/artifacts/play/2.9.3 - becouse of multiple dependencies the version of Scala is hard to find without using browser search tool. It could help if Scala version would be presented at the top. Even better if it would be presented under the `group id`, `version`
<img width="594" alt="image" src="https://github.com/scalacenter/scaladex/assets/19353690/605db2c6-01ce-440b-8c4c-ebe3a615caea">


Presenting the additional information in the artifacts page https://index.scala-lang.org/playframework/playframework/artifacts/play might be risky from the UX perspective as it might lead to having to much text, here maybe a small badge/icon for Scala LTS vs Scala Next might be useful in order to not pollute the view.

**Comment by adpi2** [comment]
Closed by #1406 

We will see later if it makes sense to add the `LTS` and `Next` tag anywhere.
