### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by jodersky** [scalacenter/scaladex#1146]
Attempting to log in by clicking the "Login" button, I receive a 503 after a few seconds. The error message is:

"The server was not able to produce a timely response to your request.
Please try again in a short while!"

- I am signed into GitHub in the same browser context in which I am trying to log in to index.scala-lang.org
- I have tried revoking and re-authorising the OAuth app, however after the authorisation phase, the timeout persists.

**Comment by adpi2** [comment]
Thanks for opening this issue.

After login we try to get a list of all the public projects of the user, its public organizations and all the public projects of its organizations. This can be quite long if the user owns a lot of projects and belongs to a lot of organization and that is why the "Login" request would timeout.

We need to rework this so that the login request triggers the retrieval of all the projects asynchronously and does not wait on it before responding.
