### ISSUE TITLE
munit-scalacheck 1.0.0 is missing from the index

### ISSUE THREAD

**Issue by mzuehlke** [scalacenter/scaladex#1443]
https://index.scala-lang.org/scalameta/munit/artifacts/munit-scalacheck

https://central.sonatype.com/artifact/org.scalameta/munit-scalacheck_3

**Comment by jypma** [comment]
Is this component by any chance using the new Sonatype Central "portal" workflow? I've been having trouble getting my library to show up on the index too:

https://central.sonatype.com/artifact/io.github.jypma/lazagna-core_3
https://mvnrepository.com/artifact/io.github.jypma/lazagna-core

Source: https://github.com/jypma/lazagna/

**Comment by adpi2** [comment]
Lazagna is here: https://index.scala-lang.org/jypma/lazagna

**Comment by jypma** [comment]
Thanks :smiley:  Interesting, I could swear I couldn't find it this morning :stuck_out_tongue:

**Comment by adpi2** [comment]
> Thanks 😃 Interesting, I could swear I couldn't find it this morning 😛

Yes it was not there, but I forced its indexing to see if it was working. And yes it does. For `munit-scalacheck` it still does not work and I have yet to find out why?

**Comment by adpi2** [comment]
Ok I think I figured everything out. So munit-scalacheck 1.0.0 is not missing, it's here: [scalameta/munit-scalacheck](https://index.scala-lang.org/scalameta/munit-scalacheck)

But all other munit-scalacheck versions are still in [scalameta/munit](https://index.scala-lang.org/scalameta/munit). Because, well, that's where they were published from.

I don't see a way for Scaladex to automatically detect that it should move those artifacts from `scalameta/munit` to `scalameta/munit-scalacheck`. It's kind of an inherent limitation of Scaladex design. But I can move them manually to reflect the change.

**Comment by adpi2** [comment]
Done! I moved all `org.scalameta:munit-scalacheck` to [scalameta/munit-scalacheck](https://index.scala-lang.org/scalameta/munit-scalacheck/artifacts/munit-scalacheck?stable-only=true#)
