### ISSUE TITLE
Search for my github org name ("wellfactored") returns some odd results

### ISSUE THREAD

**Issue by DougC** [scalacenter/scaladex#252]
Pretty sure I don't have a project named `wellfactored/sbt.settingkey$$anon$4@6f71e2d3` :-)

![safari](https://cloud.githubusercontent.com/assets/98534/17704429/ee6a5296-63cc-11e6-8e16-81a03c356945.png)

**Comment by MasseGuillaume** [comment]
the culpit is:
https://github.com/WellFactored/value-wrapper/blob/master/publishing.sbt#L19

it should be `${name.value}`

Since you cannot republish an artifact, we have a mechanism to correct those errors. Create a pull request against https://github.com/scalacenter/scaladex-data/blob/master/claims.json adding

```
"com.wellfactored play-bindings*": "WellFactored/play-bindings",
"com.wellfactored value-wrapper*": "WellFactored/value-wrapper",
```

the claims.json has precedence over pom information

**Comment by DougC** [comment]
Ok, thanks for letting me know.
