### ISSUE TITLE
Fetch Github Readme in edit Project

### ISSUE THREAD

**Issue by Scyks** [scalacenter/scaladex#291]
It would be nice to have a button/ trigger to refetch the Github readme. This could be helpful when the documentation of the project was changed.

In my case, i'd like to update the readme with deprecated / moved infos and don't wanna release again only for that reason.

**Comment by heathermiller** [comment]
> This could be helpful when the documentation of the project was changed.
Agree 100% that this is problematic. 

I really think it would be best to just to just fetch the README for everyone who loads the page. 

We should still fetch all READMEs daily (as we currently do) so we can index on them offline. Rather than displaying this README to users, we should fetch a new README on page load. Else people see stale READMEs right after they update their project pages and things like badges are pointing to the wrong versions.

**Comment by Scyks** [comment]
But fetching the Readme everytime a user loads the page have an impact on page load speed.
Github's API is fast, but still.

I'd rather recommend your second solution to fetch it daily, but then we might create a huge load which might be useless because nothing changes. Also this can have a Problem for projects which are developing in master and changing the readme to the upcoming releases. Then Scaladex would have newer readme than the version which is released.

**Comment by MasseGuillaume** [comment]
I will use the GitHub api on the client side to fetch the latest information. The server will render with the information it has and then the client will rerender with the updated information.
