### ISSUE TITLE
Organization search is case-sensitive and not consistent with GitHub

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#330]
Searching for [organization:ThoughtWorksInc](https://index.scala-lang.org/search?q=organization%3AThoughtWorksInc) yields **0** results
Searching for [organization:thoughtworksinc](https://index.scala-lang.org/search?q=organization%3Athoughtworksinc) yields **19** results

However, the GitHub organization utilizes Pascal Case: https://github.com/ThoughtWorksInc

The simplest solution is probably to make organization search case-insensitive.

**Comment by jvican** [comment]
I think the impact of this issue could be very big.
  
I suggest to lower case any search result in the backend, before hitting the Elastic Search API. Another possibility worth exploring is to check whether there are Elastic Search options to do this automatically. It's highly probable that such options exist, since case-insensitive options are often required.
  
I think that the starting point is [this file](https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/routes/api/SearchApi.scala), though this issue may also require to have a look at adjacent files in the same `server` sbt subproject.

**Comment by MasseGuillaume** [comment]
both https://index.scala-lang.org/search?q=organization%3AThoughtWorksInc and https://index.scala-lang.org/search?q=organization%3Athoughtworksinc yield the same result now. Thanks @AndySardina!

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scaladex/commit/250b6983144fc193757e91ac875b5e2d0e7dc53a
