### ISSUE TITLE
Index projecs not on GitHub (Bitbucket, etc)

### ISSUE THREAD

**Issue by adamvoss** [scalacenter/scaladex#352]
Does a facility need to exist for accessing artifacts having no SCM info?

This could be because the that information is unknown to Scaladex, the information is non-existent entirely, or the project utilizes an SCM platform that Scaladex does not support.

If this is desired, this could potentially be provided by changing the route Artifact Pages.

For example,

> https://scaladex.scala-lang.org/akka/akka-http/akka-http/10.0.1

could become

> https://scaladex.scala-lang.org/artifact/com.typesafe.akka/akka-http/10.0.1

Or some other variant based on the pom.  This has potentially pervasive implications regarding what the users see in the application.   Right now, other than installation instructions, Scaladex hides details about maven and poms and uses only see names deriving from the github repository which would no longer be the case if we are showing artifacts that do not have that information..

Action on this could affect #351

**Comment by MasseGuillaume** [comment]
Yeah, I think we should search artifacts not projects. let's give it a try.

**Comment by heathermiller** [comment]
Are you suggesting to change the URL routing structure for **all** projects? (that is, projects with and without SCM info?)

I would advise against doing this for 100% of artifacts/projects, because we're using the orgname/projectname convention from GitHub, which people have gotten used to using. Let's not change what people have already adapted to.

If you're suggesting another convention for projects _without_ SCM info, then sure. But let's not disrupt people's routine–I can't see a good reason to confuse return users for this change.
