### ISSUE TITLE
Fix footer logos

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scaladex#394]
<img width="1230" alt="screen shot 2017-03-01 at 2 24 09 pm" src="https://cloud.githubusercontent.com/assets/687163/23461596/db8d0534-fe8a-11e6-9c46-690c3416d066.png">

The alignment is a bit funny. They're a bit too big, should probably be right aligned, and have issues on mobile.

**Comment by jvican** [comment]
Scaladex uses Twirl for templating. Fixing this issue is probably some CSS tweaks away in this file https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/main.scala.html#L109.
  
I propose that logs are made smaller and aligned in the same row, possibly equally along the footer.

**Comment by MasseGuillaume** [comment]
fixed in https://github.com/scalacenter/scaladex/commit/d93881979445c0c0aba584032a53bde936c553fc
