### ISSUE TITLE
Backward compatibility for keywords search

### ISSUE THREAD

**Issue by Zhen-hao** [scalacenter/scaladex#466]
https://index.scala-lang.org/search?q=keywords%3Aakka-persistence-plugin&page=1&sort=relevant

**Comment by MasseGuillaume** [comment]
keywords was renamed to topics
https://index.scala-lang.org/search?topics=akka-persistence

This link is in the akka Doc ?

**Comment by MasseGuillaume** [comment]
Thanks for pointing this out. It look like this comes from http://akka.io/community/

We renamed keywords to topics. The correct link should now be: https://index.scala-lang.org/search?topics=akka-persistence

However the badge url is incorrect for some reason: <img src="https://index.scala-lang.org/count.svg?q=topics:akka-extension&subject=akka-extension">

**Comment by Zhen-hao** [comment]
I was using the link on this page http://akka.io/community/?_ga=2.103679618.308253065.1500461703-687766604.1494258454

Thanks for the new link!

**Comment by MasseGuillaume** [comment]
@Zhen-hao it's the same link. It's a valid issue to resolve on our side.

**Comment by MichaelViveros** [comment]
@MasseGuillaume So urls using `keywords` should be mapped to `topics` in scaladex?
Ex. https://index.scala-lang.org/search?q=keywords:akka-persistence-plugin should be mapped to https://index.scala-lang.org/search?topics=akka-persistence-plugin?

The links on http://akka.io/community/ will still lead to empty results since the keyword `akka-persistence-plugin` is replaced by the topic `akka-persistence`?

**Comment by heathermiller** [comment]
Perhaps the solution is some kind of routing trick that rewrites `q=keywords` to `topics=`?

**Comment by MasseGuillaume** [comment]
Look like http://akka.io/community/ has updated their page.
