### ISSUE TITLE
scala/scala project page sometimes throws an error (503)

### ISSUE THREAD

**Issue by MichaelViveros** [scalacenter/scaladex#469]
https://index.scala-lang.org/scala/scala/scala-library/2.12.2?target=_2.12.2

<img width="1280" alt="screen shot 2017-07-26 at 2 49 44 pm" src="https://user-images.githubusercontent.com/8866443/28638453-e8cb0510-7212-11e7-9541-dfc6b20b1eb6.png">

Doesn't always happen.

Didn't see any error in `server.log` @ index.scala-lang.org. Might be due to code that was added to get the readme client-side (scala/scala's readme is very large).

**Comment by MichaelViveros** [comment]
Throwing it all the time now

**Comment by MasseGuillaume** [comment]
@MichaelViveros taking a look thanks.

**Comment by MasseGuillaume** [comment]
It looks like 2.12.3 releases are coming strong and there is a lot of writes on elasticsearch. scala/scala has reverse dependencies on every project and always take more time to load. since elasticsearch has more work to do, it times-out. Maybe we should do a special case for this project and not compute the reverse dependencies at all.
