### ISSUE TITLE
Searching for sttp opens to an old version

### ISSUE THREAD

**Issue by adamw** [scalacenter/scaladex#497]
When searching for "sttp" and choosing the first result, it opens release 0.0.6, instead of the latest 0.0.14 (you can navigate and choose it from the dropdown).

Also, for some reason it says "2 releases", while there were a couple more

**Comment by MasseGuillaume** [comment]
https://index.scala-lang.org/artifacts/softwaremill/sttp

It looks like the last artifact we have are

* async-http-client-backend-cats
* async-http-client-backend-future

at version 0.0.14

It looks like maven central has all artifacts:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.softwaremill.sttp%22

I think the issue is the email field: <email/>

https://repo1.maven.org/maven2/com/softwaremill/sttp/core_2.11/0.0.14/core_2.11-0.0.14.pom

we need to parse the POM and it looks like it chookes on this.

**Comment by MasseGuillaume** [comment]
hum or not

http://search.maven.org/#artifactdetails%7Ccom.softwaremill.sttp%7Casync-http-client-backend-cats_2.11%7C0.0.14%7Cjar

we did index this

**Comment by adamw** [comment]
The main artifact is `core` and looking at https://index.scala-lang.org/artifacts/softwaremill/sttp for each version there's a random subset of artifacts included.

So you think there's something wrong with the pom? All the validations at sonatype pass

**Comment by MasseGuillaume** [comment]
I found the 0.0.14 pom: https://github.com/scalacenter/scaladex-index/blob/master/poms/maven-central/sha/9c47e253b7358fcc8850a04dc20ccd512871cd2e.pom

**Comment by MasseGuillaume** [comment]
ops I mean  https://github.com/scalacenter/scaladex-index/blob/master/poms/maven-central/sha/54ee5e78923e4dc8cb067c9298cb5274448e028d.pom

**Comment by MasseGuillaume** [comment]
I'm reproducing the indexing locally for sttp, I should have a fix soon.

**Comment by adamw** [comment]
thanks!

**Comment by MasseGuillaume** [comment]
It works fine locally. I'm reindexing the server.

**Comment by MasseGuillaume** [comment]
All in order now: https://index.scala-lang.org/softwaremill/sttp

**Comment by adamw** [comment]
Great, thanks! So no changes on my side needed for the future?

**Comment by MasseGuillaume** [comment]
Yep, everything is good on my side. I did not find the root of the problem, however.

**Comment by MasseGuillaume** [comment]
This should fix the issue: https://github.com/scalacenter/scaladex/pull/519
