### ISSUE TITLE
Inproper search results

### ISSUE THREAD

**Issue by peter-empen** [scalacenter/scaladex#509]
This is related to #389 but I feel even worse since misleading:

1. search for "graph": the second hit is "lewismj / cucumber". This project has nothing to do with graphs, right? Also, I'd expect "scala-graph" to pop up in the hit list but it doesn't. Note that "gremlin-scala" is a proper hit.
1. search for "scala-": no project starting with "scala-" is found. It seems there is an issue with dashes.
1. search for "scala-gr": "scala-arm", "scala-uri" are now contained, "scala-graph" is still not.
1. to get "scala-graph", having some 360 stars, you need to fully spell it out.

Looking at "scala-graph" do you see any issue that causes scaladex search to bypass the project?
What is the reason for "gramlin-scala" being included while "scala-graph" not?
Does scaladex use any black list, if so is it related?
What action is to be taken to get "scala-graph" listed on a search for "graph"?

**Comment by MasseGuillaume** [comment]
1. This is due to an artifact called graph: https://index.scala-lang.org/lewismj/cucumber/graph/0.0.6?target=_2.12. When you search for graph you see a: `Did you mean topics=graph?`.

2. The search result comes from the [query-string-syntax](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-query-string-query.html#query-string-syntax) of elasticsearch. The query would be: https://index.scala-lang.org/search?q=repository%3Ascala-*

3. Similar to 2: https://index.scala-lang.org/search?q=repository%3Ascala-gra*

I think https://index.scala-lang.org/search?q=&topics=graph gives the best result for this. Maybe the color contrast in not high enought for the warning message: `Did you mean topics=graph?`.

I agree that all of this is suboptimal. Search relevance is a hard problem and we are still willing to improve on this.

**Comment by eed3si9n** [comment]
Clicking on Akka link from the front page, I get the following..

![search__](https://user-images.githubusercontent.com/184683/34060831-76d33b10-e1b3-11e7-960f-51c2053ab5d4.png)

akka/akka doesn't show up until page 4. Could we please use GitHub star as the default sort ordering for now?

**Comment by tpolecat** [comment]
> Could we please use GitHub star as the default sort ordering for now?

 👍 from me. The "relevance" ordering still seems basically random to me. The database topic lists Quill and doobie dead last.

**Comment by peter-empen** [comment]
Looking at this again, there is an improvement concerning 1. Did you change anything?
You mentiond a message"did you mean topic..." but I have never seen such a message in Firefox.

**Comment by xingyif** [comment]
@smarter @eed3si9n what's the decision on this? are we using `Stars` as the default sorting result?

**Comment by eed3si9n** [comment]
If it's up to me I'd sort by GitHub stars, augment it with "featured" manual curation. But you'd have to ask someone from Scala Center, not me.

**Comment by eed3si9n** [comment]
Using `topics=json` as suggested by the front page, and also by the "did you mean?" feature, it shows scalatra/scalatra on top using [Relevant](https://index.scala-lang.org/search?q=*&topics=json). Curiously json4s or circe is nowhere to be found in the first few pages.

Using [Stars](https://index.scala-lang.org/search?q=*&page=1&topics=json&sort=stars), scalatra/scalatra is still on top, but at least you have circe, spray-json, jawn, play-json, scalajson, and json4s on page 1. It's actually pretty usable as the sorting. It would certainly be better if you can manually bump down web frameworks like Scalatra and Finch, but Stars is doing a better job at finding useful things.

<img width="799" alt="json" src="https://user-images.githubusercontent.com/184683/42136751-51ae5032-7d2f-11e8-8562-d3add42f59f6.png">

**Comment by MasseGuillaume** [comment]
Let's keep one ticket for relevance: https://github.com/scalacenter/scaladex/issues/389

**Comment by adpi2** [comment]
Search relevance is better since: https://github.com/scalacenter/scaladex/pull/597
