### ISSUE TITLE
Project and artifacts are out of sync.

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#550]
For example,

Scopt has Scala-Native artifacts: https://index.scala-lang.org/artifacts/scopt/scopt

But it does not list it on the project: https://index.scala-lang.org/search?q=scopt

This is because we get new releases from Maven-Central via the publish api but we do not update the project properly.

**Comment by OlegYch** [comment]
looks like the same issue here: 
`https://index.scala-lang.org/api/search?q=scalaz&target=JVM&scalaVersion=2.12.8&total=2` lists just three artifacts
`https://index.scala-lang.org/api/project?organization=scalaz&repository=scalaz&target=JVM&scalaVersion=2.12.8` lists many more

**Comment by julienrf** [comment]
Today, I’ve noticed that the latest version of `sttp` was not showing up in scaladex (https://index.scala-lang.org/softwaremill/sttp/core, Scala 2.13 is not listed as a possible target, and the last version listed is 1.1.4, although a 1.7.1 version has been published).

Interestingly, it seems that our server knows about that 1.7.1 release:

~~~
~/scaladex-index/poms/maven-central$ grep sttp/core_2.13/1.7.1 meta.json
{"created":"2019-10-07T12:54:05.000+02:00","path":"/com/softwaremill/sttp/core_2.13/1.7.1/core_2.13-1.7.1.pom","sha1":"f0b506a3b51e549aa802efa32c88301d3b65e45f"}
~~~

Running the indexing process does fix the problem. It is not clear why the index was not updated when the release was received by our server (it seems that for most of the projects, the index is up to date).

Unfortunately, there is little documentation and logging information, so it is hard to understand what went wrong.

In order to move forward, I believe we should do the following:

- Add more logging information
- Report failures (most of them are silently ignored)
- Bring resource safety / transactionality when updating the state of the system (everything is stored on the filesystem, [sometimes](https://github.com/scalacenter/scaladex/blob/8e07189fcd4c12fd43f3e3933d7f36603243f395/data/src/main/scala/ch.epfl.scala.index.data/Meta.scala#L72-L77) files of several megabytes are completely rewritten without any form of synchronization although they can be concurrently read / written)

**Comment by adpi2** [comment]
I close this issue because all the missing artifacts and releases are now correctly listed.
