### ISSUE TITLE
Improve search results for "test" and "testing" queries

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scaladex#607]
Followup of #389 but I opened a separate ticket to keep it focused on this specific query. As a beginner Scala users, I can imagine that I would like to search for testing libraries via Scaladex. Currently, the queries "testing" and "test" don't seem to return the most widely used testing frameworks at the top like ScalaTest, utest, ScalaCheck, JUnit and minitest.

https://index.scala-lang.org/search?q=test
https://index.scala-lang.org/search?q=testing
https://index.scala-lang.org/search?q=&topics=test
https://index.scala-lang.org/search?q=&topics=testing

![Screenshot 2020-03-27 at 15 16 58](https://user-images.githubusercontent.com/1408093/77771114-305e6f80-703e-11ea-839b-ab6a190ed10c.png)
![Screenshot 2020-03-27 at 15 16 45](https://user-images.githubusercontent.com/1408093/77771120-30f70600-703e-11ea-9248-a0fe802fa421.png)
![Screenshot 2020-03-27 at 15 12 41](https://user-images.githubusercontent.com/1408093/77771122-318f9c80-703e-11ea-893a-ea30b30c6ae7.png)
![Screenshot 2020-03-27 at 15 12 30](https://user-images.githubusercontent.com/1408093/77771123-32283300-703e-11ea-824a-87bc3807b5cd.png)

I wonder if there should be some manual curation for testing libraries? 🤔 Or maybe there should be a separation between testing libraries/helpers and frameworks.

**Comment by adpi2** [comment]
Thank you Olaf for opening this discussion.

My opinion is that the results of those two queries are not perfect but they are rather good:
- https://index.scala-lang.org/search?q=test
- https://index.scala-lang.org/search?q=testing

Indeed,
- they have almost the same results which is cool
- `typelevel/scalacheck` is 2nd, `scalatest/scalatest` is 3rd, `lihaoyi/utest` is 4th, `etorreborre/specs2` is 6th
- the 1st result is `holdenk/spark-testing-base` which is relevant because widely used in the large community of Spark developers
- the 5th result is `gatling/gatling` which is also relevant because its the number-one developer tool for load testing
 
Yet
- I would expect `monix/minitest` to appear on the 1st page, not the 2n
- I would like `paulbutcher/scalamock` to appear on the 1st page
- JUnit is missing, but is JUnit a scala library?

The second thing is that the results of those two other queries are rather bad:
- https://index.scala-lang.org/search?q=&topics=test
- https://index.scala-lang.org/search?q=&topics=testing

Topics are not so good for filtering because they are too arbitrary
- Some testing libraries use the `test` keyword but not the `testing` keyword or vice-versa
- A lot of projects don't use keywords at all
- Some libraries use the `test` keyword to indicate testability, eg. `twitter/finatra`.

@eed3si9n  have proposed [here](https://github.com/scalacenter/scaladex/issues/389#issuecomment-601814721) to remove the "topics=testing?" feature. It makes sense to me and I will open a dedicated issue for this.

Further than that I think that topics selection should not be considered as strict filters but as normal terms for text matching, with increased boost. It would match in github.topics but also in repository name and description.

Last but not least, I agree that we should pay attention to newcomers in scaladex. That is, scaladex must be usable enough for beginners. Having said that, scaladex is "only" the scala library index: there are other materials more suited to beginners, such as Getting Started and tutorials (Scala Book). If I was a beginner I would certainly use the testing library recommended in the official tutorials. Only then I will use scaladex to explore and find alternatives.

**Comment by olafurpg** [comment]
I agree the non-topics results are OK. I think it's a good idea to remove the "did you mean TOPIC?" suggestions.

Do you know why spark-testing-base ranks higher than ScalaTest? I can imagine ScalaTest is more widely used (both within Spark community and outside of it).

JUnit is a Java library so I guess it makes sense that it's not included. I think it might be useful to return Java results in some cases, however. For example the query "lsp" returns a result to the deprecated/archived project `scalameta/lsp4s` instead of lsp4j (which is what Metals uses). I understand it's a big change to start indexing Java libraries as weell so it's understandable if we keep things unchanged.

> Last but not least, I agree that we should pay attention to newcomers in scaladex. That is, scaladex must be usable enough for beginners. Having said that, scaladex is "only" the scala library index: there are other materials more suited to beginners, such as Getting Started and tutorials (Scala Book). If I was a beginner I would certainly use the testing library recommended in the official tutorials. Only then I will use scaladex to explore and find alternatives.

Good point 👍

**Comment by adpi2** [comment]
> Do you know why spark-testing-base ranks higher than ScalaTest? I can imagine ScalaTest is more widely used (both within Spark community and outside of it).

The repository name field is analysed with the elasticsearch standard analyzer. It means that `spark-testing-base` is analysed [`spark`, `testing`, `base`] whereas `scalatest` stays `scalatest`. When searching with the prefix `test` or `testing`, `spark-testing-base` is matched but not `scalatest`. Hence the repository name is boosted, `spark-testing-base` appears first. More information on the scoring function [here]("https://github.com/scalacenter/scaladex/issues/389#issuecomment-602649361").

> For example the query "lsp" returns a result to the deprecated/archived project scalameta/lsp4s instead of lsp4j (which is what Metals uses)

Deprecated project are tagged manually by admin users. This one is fixed.

**Comment by olafurpg** [comment]
Fair enough. Closing this since the results are already good enough 👍 

BTW, nice job with the search improvements! Really great to see Scaladex get some love again 😄
