### ISSUE TITLE
Missing artifacts in search api

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scaladex#626]
Eg https://index.scala-lang.org/api/search?q=zio&target=JVM&scalaVersion=2.13
returns 
```
{
  "organization" : "zio",
  "repository" : "zio",
  "logo" : "https://avatars2.githubusercontent.com/u/49655448?v=4",
  "artifacts" : [ "zio-test" ]
}
```

**Comment by adpi2** [comment]
@OlegYch Thank you for reporting this.

**Comment by adpi2** [comment]
I have looked into the database:
- all the releases of the project zio are correctly indexed and you can find them when you go to [zio project page](https://index.scala-lang.org/zio/zio/zio-test/1.0.0-RC21?target=_0.23)
- the project metadata are wrong because it contains only one release: `zio-test_sjs1_2.13`

I suspect that the latest maven release has erased all previous metadata of the project. If so I should be able to fix and reindex everything correctly.

**Comment by adpi2** [comment]
The bug is fixed and Scaladex has been redeployed.

**Comment by mgenereu** [comment]
Thank you!
