### ISSUE TITLE
Project on maven not found/indexed on Scaladex

### ISSUE THREAD

**Issue by jphmrst** [scalacenter/scaladex#682]
I've been trying to push a couple of small projects out, but scaladex doesn't seem to be picking them up.  Looks like they are on Maven, but after several days I don't see them on any scaladex search.

For example:  [this Github repos](https://github.com/jphmrst/scala-latex) shows up [here on Maven](https://repo1.maven.org/maven2/org/maraist/scala-latex/).

Is the push from maven to scaladex still happening? 

The POM does have the **scm** tag that I notice was a problem in some other issues, and it does point to a GitHub repos.   Any pointers or suggestions for debugging this? Thanks!

**Comment by adpi2** [comment]
Sonatype uses the binary version pattern of the artifact name to determine if an artifact is a Scala one or not. Here `scala-latex` don't have a binary version because of this setting in the build definition:
```scala
// disable publish with scala version, otherwise artifact name will
// include scala version
// e.g cassper_2.11
crossPaths := false
```

So it is not automatically pushed by Sonatype to Scaladex.

1. The easy solution would be to remove the `crossPaths := false` setting and publish a new version of the library.
2. The more tedious solution is:
- add `"org.maraist scala-latex": "pom"` in the list of [non standard Scala libraries](https://github.com/scalacenter/scaladex-contrib/blob/master/non-standard.json)
- redeploy Scaladex with the new list
- publish the pom file manually with this curl request:
```bash
curl --data-binary "@scala-latex-1.0.0.pom" \
-XPUT \
--user token:<YOUR GITHUB TOKEN> \
"http://index.scala-lang.org/publish?created=1624658400&readme=true&info=true&contributors=true&path=org/maraist/scala-latex/1.0.0/scala-latex-1.0.0.pom" 
```

**Comment by jphmrst** [comment]
Thanks --- I'm trying (1) now.  Should it matter whether the build file sets `crossPaths := true`, or just leaves the line out entirely?

**Comment by adpi2** [comment]
`crossPaths := true` is the default value so you don't need to set it in your build.sbt file

**Comment by jphmrst** [comment]
Working now --- thank you!
