### ISSUE TITLE
Scala 2.12, 3 artifacts for latest typelevel/fs2/fs2-core release are missing

### ISSUE THREAD

**Issue by rtyley** [scalacenter/scaladex#692]
On https://index.scala-lang.org/typelevel/fs2/fs2-core/3.1.0 only the Scala 2.12 artifact is present, but unfortunately the Scala 2.13 & 3 artifacts are missing:

![image](https://user-images.githubusercontent.com/52038/129453169-e22650df-3462-4c80-9fda-c185b188a1d6.png)

Those artifacts were successfully released, so far as I can see:

* https://search.maven.org/artifact/co.fs2/fs2-core_2.13/3.1.0/bundle
* https://search.maven.org/artifact/co.fs2/fs2-core_3/3.1.0/bundle

The `scm` entry in the pom correctly points to the GitHub repo, so I guess this isn't like https://github.com/scalacenter/scaladex/issues/657#issuecomment-803899871:

```
<scm>
    <url>https://github.com/typelevel/fs2</url>
    <connection>git@github.com:typelevel/fs2.git</connection>
</scm>
```

Maybe the feed from Maven Central didn't pass the relevant updates through? I wonder if the information from the Maven Central feed could be complimented with data fetched via `coursier` or something...

cc @adpi2

**Comment by adpi2** [comment]
@rtyley thanks a lot for opening this issue.

As far as I can see from the logs, all the 3 releases were added into elasticsearch at about the same time:

```log
2021-08-07 05:06:09,975 INFO  c.e.s.i.s.r.api.impl.IndexingActor:137  - Adding release MavenReference(co.fs2,fs2-core_2.12,3.1.0)
...
2021-08-07 05:06:52,071 INFO  c.e.s.i.s.r.api.impl.IndexingActor:137  - Adding release MavenReference(co.fs2,fs2-core_2.13,3.1.0)
...
2021-08-07 05:07:34,289 INFO  c.e.s.i.s.r.api.impl.IndexingActor:137  - Adding release MavenReference(co.fs2,fs2-core_3,3.1.0)
```

The total number of artifacts for the fs2 project is 5417 and the problem is there is hard limit of 5000 releases that are displayed to the user. Unfortunately this filters out the most recent ones.

https://github.com/scalacenter/scaladex/blob/e00907fe4aefcf99804b301aa241034303389e23/search/src/main/scala/ch.epfl.scala.index.search/DataRepository.scala#L245-L250


For now I think it is okay to raise this limit to 10000.

**Comment by rtyley** [comment]
> The total number of artifacts for the fs2 project is 5417 and the problem is there is hard limit of 5000 releases that are displayed to the user. Unfortunately this filters out the most recent ones.

Thanks @adpi2 ! Wow, that's a lot of artifacts! I wonder if it's worth adding a descending sort on the `created` field too, as I guess users are usually most interested in the most recent releases?

**Comment by adpi2** [comment]
I wondered the same. I am not sure if it's a good idea because some organizations are stuck on old versions. I hope it is always possible to show all artifacts and if it is not maybe we could page it.

In the case of fs2 specifically I see there are a lot of intermediate versions like `3.0-fe9753c` which explain why there are so many artifacts. Maybe we don't need them and we should filter them out. And actually there is a button just for that in the Edit page of the project.
