### ISSUE TITLE
URL style is broken, does not allow for duplicate artifact names

### ISSUE THREAD

**Issue by timperrett** [scalacenter/scaladex#86]
Given: https://index.scala-lang.org/oncue/core and then https://index.scala-lang.org/oncue/typesafe - it is impossible to find the Knobs core module. 

Seems like there is some bug or bad assumption in the parsing / use of the group id in Scaladex. Some artifacts are just not discoverable at all (note this is not to do with search, so its not clear if the core module was indexed or not, rather, the URL scheme does not allow me to find it)

**Comment by MasseGuillaume** [comment]
@timperrett 

I'm using github as a namespace since not everyone is using subdomains in their groupId.
It now looks like:
https://index.scala-lang.org/oncue/knobs/typesafe
https://index.scala-lang.org/oncue/knobs/core
https://index.scala-lang.org/oncue/knobs/core/3.6.1
https://index.scala-lang.org/oncue/knobs/core_2.10/3.6.1

sometime it's a bit repetitive:
https://index.scala-lang.org/typelevel/cats/cats-core

I'm also open to use groupId. However in practice this would require some changes in the community. For example:
`"org.typelevel" %% "cats-core"` should be `"org.typelevel.cats" %% "core"`

You can also find organization's artifact here:
https://index.scala-lang.org/search?q=organization:oncue
