### ISSUE TITLE
Click on the Login button results in page not found.

### ISSUE THREAD

**Issue by nikolakasev** [scalacenter/scaladex#87]
Page isn't found because the callback is made to http://localhost:8080/callback?code=1064084d9f3e80229ea3 for example.

**Comment by xuwei-k** [comment]
https://github.com/scalacenter/scaladex/blob/91d9ea220915a60cf417afc79dc171563fa6abcf/webapp/jvm/src/main/scala/ch.epfl.scala.index.server/Github.scala#L57

**Comment by Scyks** [comment]
It seems like that the redirect URL is configured in the application on github itself. It's not possible to modify this url from the app itself because it have to match to the defined one.

When you change the URL in the Github app (from documentation: https://developer.github.com/v3/oauth/#redirect-urls you need to specify a redirect url.) then the development mode will not work any longer.

To fix this, we can:
* create a second app for local development
* remove the `rediect_uri` param from source code because there is no need for
* implement kind of config to specify the app client configurations `client_secret` & `client_id` which are right now hard coded.
* for config, we can use Hocon: https://github.com/typesafehub/config

If it's possible to specify more than one redirect uri's, we can change the url in the source code, which means to extract the url from the current request. But this will also lead to problems if the uri is not configured.

What do you think?

**Comment by MasseGuillaume** [comment]
Totally. I did not had time to finish this feature.

This is what I'm currently working on. https://waffle.io/scalacenter/scaladex

**Comment by MasseGuillaume** [comment]
fixed in #193

You should now be able to login. Once you do you can click on your avatar to get a list of your projects.
